var m1Design = function() { m1Design = {}; var c="#m1-UNT_Appv2";var d="NEVER";var e="UNT_Appv2";var f="_resizing";var g="ajaxPageReloadApproach";var h="css";var i="data-layout-content-height";var k="e0";var l="e1";var m="e10";var n="e11";var o="e12";var p="e13";var q="e14";var r="e15";var s="e16";var t="e17";var u="e18";var v="e19";var w="e2";var x="e26";var y="e27";var z="e3";var A="e33";var B="e34";var C="e35";var D="e36";var E="e38";var F="e4";var G="e40";var H="e5";var I="e6";var J="e7";var K="e8";var L="e9";var M="m1-";var N="m1-UNT-Appv2-Map-box";
var O="m1-UNT-Appv2-Map-box-scroller";var P="m1-UNT-Appv2-ParkingStatus-box";var Q="m1-UNT-Appv2-ParkingStatus-box-scroller";var R="m1-UNT-Appv2-Settings-box";var S="m1-UNT-Appv2-Settings-box-scroller";var T="m1-UNT-Appv2-map1";var U="m1-UNT-Appv2-multiPage1";var V="m1-UNT-Appv2-tabBar1";var W="m1-UNT-Appv2-tabBar1-Map";var X="m1-UNT-Appv2-tabBar1-Map-img";var Y="m1-UNT-Appv2-tabBar1-ParkingStatus";var Z="m1-UNT-Appv2-tabBar1-ParkingStatus-img";var aa="m1-UNT-Appv2-tabBar1-Settings";var ba="m1-UNT-Appv2-tabBar1-Settings-img";
var ca="m1-UNT-Appv2-text1";var da="m1-UNT-Appv2-text2";var ea="m1-UNT-Appv2-text3";var fa="m1-UNT-Appv2-text4";var ga="pages";var $="px";var ha="root";var ia="shouldHideAddressBar";var ja="softSpinnerEnabled";
(function(){var ka=function(j){return M+j};var ma={"UNT_Appv2":{"id":e,"anchor_id":c,"resize":function(j,la){var a;var b={};var na;a=b[l]={w:j,h:la,py:0};try{a=b[k]={e:document.getElementById(U),w:0,h:0,py:0,p:b[l]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=Math.max((a.p.h+-49)*1,0)+$;a.e.style.top=0+-a.p.py+$;a.h=Math.max((a.p.h+-49)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-49)*1,0),0)}catch(oa){}try{a=b[F]={w:0,h:0,py:0,p:b[k]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=Math.max((a.p.h+-0.0)*
1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(pa){}try{a=b[z]={e:document.getElementById(P),w:0,h:0,py:0,p:b[F]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=Math.max((a.p.h+-0.0)*1,0)+$;a.e.style.top=0+-a.p.py+$;a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(qa){}try{a=b[H]={e:document.getElementById(Q),w:0,h:0,py:0,p:b[z]};a.conth=a.e.getAttribute(i);a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=(a.conth||(181<Math.max((a.p.h+-0.0)*
1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0))))+$;a.e.style.top=0+-a.p.py+$;a.h=a.conth||(181<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0)));a.p.py=a.p.py+Math.max(a.conth||(181<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0))),0+0)}catch(ra){}try{a=b[I]={w:0,h:0,py:0,p:b[H]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=43;a.p.py=a.p.py+Math.max(43,0)}catch(sa){}try{a=b[J]={e:document.getElementById(ea),
w:0,h:0,py:0,p:b[I]};a.e.style.width=136+$;a.e.style.left=(a.p.w+-136)*0.5+$;a.w=136;a.e.style.height=23+$;a.e.style.top=(a.p.h+-33)*1+-a.p.py+$;a.h=23;a.p.py=a.p.py+Math.max(23,0)}catch(ta){}try{a=b[K]={w:0,h:0,py:0,p:b[H]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=56;a.p.py=a.p.py+Math.max(56,0)}catch(ua){}try{a=b[L]={e:document.getElementById(fa),w:0,h:0,py:0,p:b[K]};a.e.style.width=151+$;a.e.style.left=(a.p.w+-151)*0.497+$;a.w=151;a.e.style.height=29+$;a.e.style.top=(a.p.h+-36)*1+-a.p.py+$;a.h=29;a.p.py=
a.p.py+Math.max(29,0)}catch(va){}try{a=b[n]={w:0,h:0,py:0,p:b[k]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(wa){}try{a=b[m]={e:document.getElementById(N),w:0,h:0,py:0,p:b[n]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=Math.max((a.p.h+-0.0)*1,0)+$;a.e.style.top=0+-a.p.py+$;a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(xa){}try{a=b[o]={e:document.getElementById(O),w:0,h:0,
py:0,p:b[m]};a.conth=a.e.getAttribute(i);a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=(a.conth||(411<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0))))+$;a.e.style.top=0+-a.p.py+$;a.h=a.conth||(411<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0)));a.p.py=a.p.py+Math.max(a.conth||(411<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0))),0+0)}catch(ya){}try{a=b[p]=
{w:0,h:0,py:0,p:b[o]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=43;a.p.py=a.p.py+Math.max(43,0)}catch(za){}try{a=b[q]={e:document.getElementById(da),w:0,h:0,py:0,p:b[p]};a.e.style.width=40+$;a.e.style.left=(a.p.w+-40)*0.5+$;a.w=40;a.e.style.height=23+$;a.e.style.top=(a.p.h+-33)*1+-a.p.py+$;a.h=23;a.p.py=a.p.py+Math.max(23,0)}catch(Aa){}try{a=b[r]={w:0,h:0,py:0,p:b[o]};a.w=320;a.h=368;a.p.py=a.p.py+Math.max(368,0)}catch(Ba){}try{a=b[s]={e:document.getElementById(T),w:0,h:0,py:0,p:b[r]};a.conth=a.e.getAttribute(i);
a.w=Math.max((a.p.w+-2)*1,0);a.e.style.height=(a.conth||(-1<Math.max((a.p.h+-2)*1,0)?Math.max((a.p.h+-2)*1,0):Math.max(366,Math.max((a.p.h+-2)*1,0))))+$;a.e.style.top=0+-a.p.py+$;a.h=a.conth||(-1<Math.max((a.p.h+-2)*1,0)?Math.max((a.p.h+-2)*1,0):Math.max(366,Math.max((a.p.h+-2)*1,0)));a.p.py=a.p.py+Math.max(a.conth||(-1<Math.max((a.p.h+-2)*1,0)?Math.max((a.p.h+-2)*1,0):Math.max(366,Math.max((a.p.h+-2)*1,0))),0+0)}catch(Ca){}try{a=b[u]={w:0,h:0,py:0,p:b[k]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=Math.max((a.p.h+
-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(Da){}try{a=b[t]={e:document.getElementById(R),w:0,h:0,py:0,p:b[u]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=Math.max((a.p.h+-0.0)*1,0)+$;a.e.style.top=0+-a.p.py+$;a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(Ea){}try{a=b[v]={e:document.getElementById(S),w:0,h:0,py:0,p:b[t]};a.conth=a.e.getAttribute(i);a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=(a.conth||(180<Math.max((a.p.h+
-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0))))+$;a.e.style.top=0+-a.p.py+$;a.h=a.conth||(180<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0)));a.p.py=a.p.py+Math.max(a.conth||(180<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0))),0+0)}catch(Fa){}try{a=b[x]={w:0,h:0,py:0,p:b[v]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=43;a.p.py=a.p.py+Math.max(43,0)}catch(Ga){}try{a=b[y]={e:document.getElementById(ca),
w:0,h:0,py:0,p:b[x]};a.e.style.width=76+$;a.e.style.left=(a.p.w+-76)*0.5+$;a.w=76;a.e.style.height=23+$;a.e.style.top=(a.p.h+-33)*1+-a.p.py+$;a.h=23;a.p.py=a.p.py+Math.max(23,0)}catch(Ha){}try{a=b[w]={e:document.getElementById(V),w:0,h:0,py:0,p:b[l]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=49+$;a.e.style.top=(a.p.h+-49)*1+-a.p.py+$;a.h=49;a.p.py=a.p.py+Math.max(49,0)}catch(Ia){}try{a=b[A]={e:document.getElementById(Y),w:0,h:0,py:0,p:b[w]};a.e.style.width=Math.max((a.p.w+-0.0)*0.3125,0)+$;
a.e.style.left=(a.p.w+-0.0)*0.0094+$;a.w=Math.max((a.p.w+-0.0)*0.3125,0);a.e.style.height=Math.max((a.p.h+-6)*1,0)+$;a.e.style.top=3+-a.p.py+$;a.h=Math.max((a.p.h+-6)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-6)*1,0),0)}catch(Ja){}try{a=b[D]={e:document.getElementById(Z),w:0,h:0,py:0,p:b[A]};a.e.style.width=16+$;a.e.style.left=(a.p.w+-16)*0.5+$;a.w=16;a.h=16;a.p.py=a.p.py+Math.max(16,0)}catch(Ka){}try{a=b[B]={e:document.getElementById(W),w:0,h:0,py:0,p:b[w]};a.e.style.width=Math.max((a.p.w+-0.0)*
0.3125,0)+$;a.e.style.left=(a.p.w+-0.0)*0.3406+$;a.w=Math.max((a.p.w+-0.0)*0.3125,0);a.e.style.height=Math.max((a.p.h+-6)*1,0)+$;a.e.style.top=3+-a.p.py+$;a.h=Math.max((a.p.h+-6)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-6)*1,0),0)}catch(La){}try{a=b[E]={e:document.getElementById(X),w:0,h:0,py:0,p:b[B]};a.e.style.width=16+$;a.e.style.left=(a.p.w+-16)*0.5+$;a.w=16;a.h=16;a.p.py=a.p.py+Math.max(16,0)}catch(Ma){}try{a=b[C]={e:document.getElementById(aa),w:0,h:0,py:0,p:b[w]};a.e.style.width=Math.max((a.p.w+
-0.0)*0.3125,0)+$;a.e.style.left=(a.p.w+-0.0)*0.6719+$;a.w=Math.max((a.p.w+-0.0)*0.3125,0);a.e.style.height=Math.max((a.p.h+-6)*1,0)+$;a.e.style.top=3+-a.p.py+$;a.h=Math.max((a.p.h+-6)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-6)*1,0),0)}catch(Na){}try{a=b[G]={e:document.getElementById(ba),w:0,h:0,py:0,p:b[C]};a.e.style.width=16+$;a.e.style.left=(a.p.w+-16)*0.5+$;a.w=16;a.h=16;a.p.py=a.p.py+Math.max(16,0)}catch(Oa){}}}};m1Design[h]=ka;m1Design[ga]=ma;m1Design[f]={};m1Design[g]=d;m1Design[ja]=true;
m1Design[ia]=true;m1Design[ha]=function(){return e}})(); return m1Design; }();m1Design.actions={'action1':function() { phoneui.gotoMultiPagePage('m1-UNT-Appv2-multiPage1', 'SET_PAGE', 'm1-UNT-Appv2-Map', 'NONE');},
'action0':function() { phoneui.gotoMultiPagePage('m1-UNT-Appv2-multiPage1', 'SET_PAGE', 'm1-UNT-Appv2-ParkingStatus', 'NONE');},
'action2':function() { phoneui.gotoMultiPagePage('m1-UNT-Appv2-multiPage1', 'SET_PAGE', 'm1-UNT-Appv2-Settings', 'NONE');}};
;
