var m1Design = function() { m1Design = {}; var c="#m1-UNT_Appv2";var d="NEVER";var e="UNT_Appv2";var f="_resizing";var g="ajaxPageReloadApproach";var h="css";var i="data-layout-content-height";var k="e0";var l="e1";var m="e10";var n="e11";var o="e12";var p="e13";var q="e14";var r="e15";var s="e16";var t="e17";var u="e18";var v="e19";var w="e2";var x="e20";var y="e21";var z="e22";var A="e23";var B="e25";var C="e26";var D="e27";var E="e3";var F="e34";var G="e35";var H="e4";var I="e41";var J="e42";var K="e43";var L="e44";var M="e46";var N="e48";
var O="e5";var P="e6";var Q="e7";var R="e8";var S="e9";var T="m1-";var U="m1-UNT-Appv2-Map-box";var V="m1-UNT-Appv2-MapOfGarage";var W="m1-UNT-Appv2-ParkingStatus-box";var X="m1-UNT-Appv2-ParkingStatus-box-scroller";var Y="m1-UNT-Appv2-Settings-box";var Z="m1-UNT-Appv2-Settings-box-scroller";var aa="m1-UNT-Appv2-multiPage1";var ba="m1-UNT-Appv2-tabBar";var ca="m1-UNT-Appv2-tabBar-Map";var da="m1-UNT-Appv2-tabBar-Map-img";var ea="m1-UNT-Appv2-tabBar-ParkingStatus";var fa="m1-UNT-Appv2-tabBar-ParkingStatus-img";
var ga="m1-UNT-Appv2-tabBar-Settings";var ha="m1-UNT-Appv2-tabBar-Settings-img";var ia="m1-UNT-Appv2-text1";var ja="m1-UNT-Appv2-text2";var ka="m1-UNT-Appv2-text3";var la="m1-UNT-Appv2-text4";var ma="m1-UNT-Appv2-text5";var na="m1-UNT-Appv2-text6";var oa="m1-UNT-Appv2-text7";var pa="m1-UNT-Appv2-text8";var qa="pages";var $="px";var ra="root";var sa="shouldHideAddressBar";var ta="softSpinnerEnabled";
(function(){var ua=function(j){return T+j};var wa={"UNT_Appv2":{"id":e,"anchor_id":c,"resize":function(j,va){var a;var b={};var xa;a=b[l]={w:j,h:va,py:0};try{a=b[k]={e:document.getElementById(aa),w:0,h:0,py:0,p:b[l]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=Math.max((a.p.h+-49)*1,0)+$;a.e.style.top=0+-a.p.py+$;a.h=Math.max((a.p.h+-49)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-49)*1,0),0)}catch(ya){}try{a=b[H]={w:0,h:0,py:0,p:b[k]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=Math.max((a.p.h+-0.0)*
1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(za){}try{a=b[E]={e:document.getElementById(U),w:0,h:0,py:0,p:b[H]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=Math.max((a.p.h+-0.0)*1,0)+$;a.e.style.top=0+-a.p.py+$;a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(Aa){}try{a=b[O]={w:0,h:0,py:0,p:b[E]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=43;a.p.py=a.p.py+Math.max(43,0)}catch(Ba){}try{a=b[P]={e:document.getElementById(ja),w:0,h:0,py:0,p:b[O]};
a.e.style.width=40+$;a.e.style.left=(a.p.w+-40)*0.5+$;a.w=40;a.e.style.height=23+$;a.e.style.top=(a.p.h+-33)*1+-a.p.py+$;a.h=23;a.p.py=a.p.py+Math.max(23,0)}catch(Ca){}try{a=b[Q]={w:0,h:0,py:0,p:b[E]};a.w=320;a.h=368;a.p.py=a.p.py+Math.max(368,0)}catch(Da){}try{a=b[R]={e:document.getElementById(V),w:0,h:0,py:0,p:b[Q]};a.conth=a.e.getAttribute(i);a.w=Math.max((a.p.w+-2)*1,0);a.e.style.height=(a.conth||(-1<Math.max((a.p.h+-2)*1,0)?Math.max((a.p.h+-2)*1,0):Math.max(366,Math.max((a.p.h+-2)*1,0))))+$;
a.e.style.top=0+-a.p.py+$;a.h=a.conth||(-1<Math.max((a.p.h+-2)*1,0)?Math.max((a.p.h+-2)*1,0):Math.max(366,Math.max((a.p.h+-2)*1,0)));a.p.py=a.p.py+Math.max(a.conth||(-1<Math.max((a.p.h+-2)*1,0)?Math.max((a.p.h+-2)*1,0):Math.max(366,Math.max((a.p.h+-2)*1,0))),0+0)}catch(Ea){}try{a=b[m]={w:0,h:0,py:0,p:b[k]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(Fa){}try{a=b[S]={e:document.getElementById(W),w:0,h:0,py:0,p:b[m]};a.w=Math.max((a.p.w+
-0.0)*1,0);a.e.style.height=Math.max((a.p.h+-0.0)*1,0)+$;a.e.style.top=0+-a.p.py+$;a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(Ga){}try{a=b[n]={e:document.getElementById(X),w:0,h:0,py:0,p:b[S]};a.conth=a.e.getAttribute(i);a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=(a.conth||(2147483647<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(511,Math.max((a.p.h+-0.0)*1,0))))+$;a.e.style.top=0+-a.p.py+$;a.h=a.conth||(2147483647<Math.max((a.p.h+
-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(511,Math.max((a.p.h+-0.0)*1,0)));a.p.py=a.p.py+Math.max(a.conth||(2147483647<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(511,Math.max((a.p.h+-0.0)*1,0))),0+0)}catch(Ha){}try{a=b[o]={w:0,h:0,py:0,p:b[n]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=43;a.p.py=a.p.py+Math.max(43,0)}catch(Ia){}try{a=b[p]={e:document.getElementById(ka),w:0,h:0,py:0,p:b[o]};a.e.style.width=136+$;a.e.style.left=(a.p.w+-136)*0.5+$;a.w=136;a.e.style.height=23+$;a.e.style.top=
(a.p.h+-33)*1+-a.p.py+$;a.h=23;a.p.py=a.p.py+Math.max(23,0)}catch(Ja){}try{a=b[q]={w:0,h:0,py:0,p:b[n]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=56;a.p.py=a.p.py+Math.max(56,0)}catch(Ka){}try{a=b[r]={e:document.getElementById(la),w:0,h:0,py:0,p:b[q]};a.e.style.width=151+$;a.e.style.left=(a.p.w+-151)*0.497+$;a.w=151;a.e.style.height=29+$;a.e.style.top=(a.p.h+-36)*1+-a.p.py+$;a.h=29;a.p.py=a.p.py+Math.max(29,0)}catch(La){}try{a=b[s]={w:0,h:0,py:0,p:b[n]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=56;a.p.py=a.p.py+
Math.max(56,0)}catch(Ma){}try{a=b[t]={e:document.getElementById(na),w:0,h:0,py:0,p:b[s]};a.e.style.width=151+$;a.e.style.left=(a.p.w+-151)*0.497+$;a.w=151;a.e.style.height=29+$;a.e.style.top=(a.p.h+-36)*1+-a.p.py+$;a.h=29;a.p.py=a.p.py+Math.max(29,0)}catch(Na){}try{a=b[u]={w:0,h:0,py:0,p:b[n]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=56;a.p.py=a.p.py+Math.max(56,0)}catch(Oa){}try{a=b[v]={e:document.getElementById(oa),w:0,h:0,py:0,p:b[u]};a.e.style.width=151+$;a.e.style.left=(a.p.w+-151)*0.497+$;a.w=151;
a.e.style.height=29+$;a.e.style.top=(a.p.h+-36)*1+-a.p.py+$;a.h=29;a.p.py=a.p.py+Math.max(29,0)}catch(Pa){}try{a=b[x]={w:0,h:0,py:0,p:b[n]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=56;a.p.py=a.p.py+Math.max(56,0)}catch(Qa){}try{a=b[y]={e:document.getElementById(ma),w:0,h:0,py:0,p:b[x]};a.e.style.width=151+$;a.e.style.left=(a.p.w+-151)*0.497+$;a.w=151;a.e.style.height=29+$;a.e.style.top=(a.p.h+-36)*1+-a.p.py+$;a.h=29;a.p.py=a.p.py+Math.max(29,0)}catch(Ra){}try{a=b[z]={w:0,h:0,py:0,p:b[n]};a.w=Math.max((a.p.w+
-0.0)*1,0);a.h=56;a.p.py=a.p.py+Math.max(56,0)}catch(Sa){}try{a=b[A]={e:document.getElementById(pa),w:0,h:0,py:0,p:b[z]};a.e.style.width=151+$;a.e.style.left=(a.p.w+-151)*0.497+$;a.w=151;a.e.style.height=29+$;a.e.style.top=(a.p.h+-36)*1+-a.p.py+$;a.h=29;a.p.py=a.p.py+Math.max(29,0)}catch(Ta){}try{a=b[C]={w:0,h:0,py:0,p:b[k]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(Ua){}try{a=b[B]={e:document.getElementById(Y),w:0,h:0,
py:0,p:b[C]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=Math.max((a.p.h+-0.0)*1,0)+$;a.e.style.top=0+-a.p.py+$;a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(Va){}try{a=b[D]={e:document.getElementById(Z),w:0,h:0,py:0,p:b[B]};a.conth=a.e.getAttribute(i);a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=(a.conth||(180<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0))))+$;a.e.style.top=0+-a.p.py+$;a.h=a.conth||
(180<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0)));a.p.py=a.p.py+Math.max(a.conth||(180<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0))),0+0)}catch(Wa){}try{a=b[F]={w:0,h:0,py:0,p:b[D]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=43;a.p.py=a.p.py+Math.max(43,0)}catch(Xa){}try{a=b[G]={e:document.getElementById(ia),w:0,h:0,py:0,p:b[F]};a.e.style.width=76+$;a.e.style.left=(a.p.w+-76)*0.5+$;a.w=76;a.e.style.height=
23+$;a.e.style.top=(a.p.h+-33)*1+-a.p.py+$;a.h=23;a.p.py=a.p.py+Math.max(23,0)}catch(Ya){}try{a=b[w]={e:document.getElementById(ba),w:0,h:0,py:0,p:b[l]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=49+$;a.e.style.top=(a.p.h+-49)*1+-a.p.py+$;a.h=49;a.p.py=a.p.py+Math.max(49,0)}catch(Za){}try{a=b[I]={e:document.getElementById(ca),w:0,h:0,py:0,p:b[w]};a.e.style.width=Math.max((a.p.w+-0.0)*0.3125,0)+$;a.e.style.left=(a.p.w+-0.0)*0.0094+$;a.w=Math.max((a.p.w+-0.0)*0.3125,0);a.e.style.height=Math.max((a.p.h+
-6)*1,0)+$;a.e.style.top=3+-a.p.py+$;a.h=Math.max((a.p.h+-6)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-6)*1,0),0)}catch($a){}try{a=b[L]={e:document.getElementById(da),w:0,h:0,py:0,p:b[I]};a.e.style.width=16+$;a.e.style.left=(a.p.w+-16)*0.5+$;a.w=16;a.h=16;a.p.py=a.p.py+Math.max(16,0)}catch(ab){}try{a=b[J]={e:document.getElementById(ea),w:0,h:0,py:0,p:b[w]};a.e.style.width=Math.max((a.p.w+-0.0)*0.3125,0)+$;a.e.style.left=(a.p.w+-0.0)*0.3406+$;a.w=Math.max((a.p.w+-0.0)*0.3125,0);a.e.style.height=
Math.max((a.p.h+-6)*1,0)+$;a.e.style.top=3+-a.p.py+$;a.h=Math.max((a.p.h+-6)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-6)*1,0),0)}catch(bb){}try{a=b[M]={e:document.getElementById(fa),w:0,h:0,py:0,p:b[J]};a.e.style.width=16+$;a.e.style.left=(a.p.w+-16)*0.5+$;a.w=16;a.h=16;a.p.py=a.p.py+Math.max(16,0)}catch(cb){}try{a=b[K]={e:document.getElementById(ga),w:0,h:0,py:0,p:b[w]};a.e.style.width=Math.max((a.p.w+-0.0)*0.3125,0)+$;a.e.style.left=(a.p.w+-0.0)*0.6719+$;a.w=Math.max((a.p.w+-0.0)*0.3125,0);
a.e.style.height=Math.max((a.p.h+-6)*1,0)+$;a.e.style.top=3+-a.p.py+$;a.h=Math.max((a.p.h+-6)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-6)*1,0),0)}catch(db){}try{a=b[N]={e:document.getElementById(ha),w:0,h:0,py:0,p:b[K]};a.e.style.width=16+$;a.e.style.left=(a.p.w+-16)*0.5+$;a.w=16;a.h=16;a.p.py=a.p.py+Math.max(16,0)}catch(eb){}}}};m1Design[h]=ua;m1Design[qa]=wa;m1Design[f]={};m1Design[g]=d;m1Design[ta]=true;m1Design[sa]=true;m1Design[ra]=function(){return e}})(); return m1Design; }();m1Design.actions={'action0':function() { phoneui.gotoMultiPagePage('m1-UNT-Appv2-multiPage1', 'SET_PAGE', 'm1-UNT-Appv2-Map', 'NONE');},
'action1':function() { phoneui.gotoMultiPagePage('m1-UNT-Appv2-multiPage1', 'SET_PAGE', 'm1-UNT-Appv2-ParkingStatus', 'NONE');},
'action2':function() { phoneui.gotoMultiPagePage('m1-UNT-Appv2-multiPage1', 'SET_PAGE', 'm1-UNT-Appv2-Settings', 'NONE');}};
;
