var m1Design = function() { m1Design = {}; var c="#m1-UNT_Appv2";var f="#m1-landing";var g="#m1-list";var h="NEVER";var i="UNT_Appv2";var j="_resizing";var k="ajaxPageReloadApproach";var l="css";var m="data-layout-content-height";var n="e0";var o="e1";var p="e10";var q="e11";var r="e12";var s="e14";var t="e15";var u="e16";var v="e2";var w="e23";var x="e24";var y="e3";var z="e30";var A="e31";var B="e32";var C="e33";var D="e35";var E="e37";var F="e4";var G="e41";var H="e42";var O="e43";var P="e44";var Q="e45";var R="e46";var S="e49";var T="e5";
var U="e50";var aa="e51";var ba="e52";var ca="e53";var da="e54";var V="e55";var ea="e56";var W="e57";var fa="e58";var X="e59";var ga="e6";var ha="e60";var Y="e7";var ia="e8";var Z="e9";var ja="landing";var ka="list";var la="m1-";var ma="m1-UNT-Appv2-DiscountStatus-box";var na="m1-UNT-Appv2-Map-box";var oa="m1-UNT-Appv2-MapOfGarage";var pa="m1-UNT-Appv2-Settings-box";var qa="m1-UNT-Appv2-Settings-box-scroller";var ra="m1-UNT-Appv2-multiPage1";var sa="m1-UNT-Appv2-tabBar";var ta="m1-UNT-Appv2-tabBar-DiscountStatus";
var ua="m1-UNT-Appv2-tabBar-DiscountStatus-img";var va="m1-UNT-Appv2-tabBar-Map";var wa="m1-UNT-Appv2-tabBar-Map-img";var xa="m1-UNT-Appv2-tabBar-Settings";var ya="m1-UNT-Appv2-tabBar-Settings-img";var za="m1-UNT-Appv2-text1";var Aa="m1-UNT-Appv2-text2";var Ba="m1-UNT-Appv2-text3";var Ca="m1-images-preloader";var Da="m1-landing-back1";var Ea="m1-landing-landingMap";var Fa="m1-landing-text1";var Ga="m1-list-accessoryImage1";var Ha="m1-list-back1";var Ia="m1-list-listItem1-inner-div";var Ja="m1-list-navigation1";
var Ka="m1-list-panel1";var La="m1-list-panel1-scroller";var Ma="m1-list-text1";var Na="m1-list-text2";var Oa="pages";var $="px";var Pa="root";var Qa="shouldHideAddressBar";var Ra="softSpinnerEnabled";
(function(){var Sa=function(d){return la+d};var Za={"UNT_Appv2":{"id":i,"anchor_id":c,"resize":function(d,e){var a;var b={};var I;a=b[o]={w:d,h:e,py:0};try{a=b[n]={e:document.getElementById(ra),w:0,h:0,py:0,p:b[o]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=Math.max((a.p.h+-49)*1,0)+$;a.e.style.top=0+-a.p.py+$;a.h=Math.max((a.p.h+-49)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-49)*1,0),0)}catch(J){}try{a=b[F]={w:0,h:0,py:0,p:b[n]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=Math.max((a.p.h+-0.0)*1,
0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(K){}try{a=b[y]={e:document.getElementById(na),w:0,h:0,py:0,p:b[F]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=Math.max((a.p.h+-0.0)*1,0)+$;a.e.style.top=0+-a.p.py+$;a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(L){}try{a=b[T]={w:0,h:0,py:0,p:b[y]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=43;a.p.py=a.p.py+Math.max(43,0)}catch(M){}try{a=b[ga]={e:document.getElementById(Aa),w:0,h:0,py:0,p:b[T]};a.e.style.width=
40+$;a.e.style.left=(a.p.w+-40)*0.5+$;a.w=40;a.e.style.height=23+$;a.e.style.top=(a.p.h+-33)*1+-a.p.py+$;a.h=23;a.p.py=a.p.py+Math.max(23,0)}catch(N){}try{a=b[Y]={w:0,h:0,py:0,p:b[y]};a.w=320;a.h=368;a.p.py=a.p.py+Math.max(368,0)}catch(Ta){}try{a=b[ia]={e:document.getElementById(oa),w:0,h:0,py:0,p:b[Y]};a.conth=a.e.getAttribute(m);a.w=Math.max((a.p.w+-2)*1,0);a.e.style.height=(a.conth||(-1<Math.max((a.p.h+-2)*1,0)?Math.max((a.p.h+-2)*1,0):Math.max(366,Math.max((a.p.h+-2)*1,0))))+$;a.e.style.top=0+
-a.p.py+$;a.h=a.conth||(-1<Math.max((a.p.h+-2)*1,0)?Math.max((a.p.h+-2)*1,0):Math.max(366,Math.max((a.p.h+-2)*1,0)));a.p.py=a.p.py+Math.max(a.conth||(-1<Math.max((a.p.h+-2)*1,0)?Math.max((a.p.h+-2)*1,0):Math.max(366,Math.max((a.p.h+-2)*1,0))),0+0)}catch(Ua){}try{a=b[p]={w:0,h:0,py:0,p:b[n]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(Va){}try{a=b[Z]={e:document.getElementById(ma),w:0,h:0,py:0,p:b[p]};a.w=Math.max((a.p.w+
-0.0)*1,0);a.e.style.height=Math.max((a.p.h+-0.0)*1,0)+$;a.e.style.top=0+-a.p.py+$;a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(Wa){}try{a=b[q]={w:0,h:0,py:0,p:b[Z]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=43;a.p.py=a.p.py+Math.max(43,0)}catch(Xa){}try{a=b[r]={e:document.getElementById(Ba),w:0,h:0,py:0,p:b[q]};a.e.style.width=147+$;a.e.style.left=(a.p.w+-147)*0.4971+$;a.w=147;a.e.style.height=23+$;a.e.style.top=(a.p.h+-33)*1+-a.p.py+$;a.h=23;a.p.py=a.p.py+Math.max(23,
0)}catch(Ya){}try{a=b[t]={w:0,h:0,py:0,p:b[n]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch($a){}try{a=b[s]={e:document.getElementById(pa),w:0,h:0,py:0,p:b[t]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=Math.max((a.p.h+-0.0)*1,0)+$;a.e.style.top=0+-a.p.py+$;a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(ab){}try{a=b[u]={e:document.getElementById(qa),w:0,h:0,py:0,p:b[s]};a.conth=
a.e.getAttribute(m);a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=(a.conth||(180<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0))))+$;a.e.style.top=0+-a.p.py+$;a.h=a.conth||(180<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0)));a.p.py=a.p.py+Math.max(a.conth||(180<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0))),0+0)}catch(bb){}try{a=b[w]={w:0,h:0,py:0,p:b[u]};
a.w=Math.max((a.p.w+-0.0)*1,0);a.h=43;a.p.py=a.p.py+Math.max(43,0)}catch(cb){}try{a=b[x]={e:document.getElementById(za),w:0,h:0,py:0,p:b[w]};a.e.style.width=76+$;a.e.style.left=(a.p.w+-76)*0.5+$;a.w=76;a.e.style.height=23+$;a.e.style.top=(a.p.h+-33)*1+-a.p.py+$;a.h=23;a.p.py=a.p.py+Math.max(23,0)}catch(db){}try{a=b[v]={e:document.getElementById(sa),w:0,h:0,py:0,p:b[o]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=49+$;a.e.style.top=(a.p.h+-49)*1+-a.p.py+$;a.h=49;a.p.py=a.p.py+Math.max(49,0)}catch(eb){}try{a=
b[z]={e:document.getElementById(va),w:0,h:0,py:0,p:b[v]};a.e.style.width=Math.max((a.p.w+-0.0)*0.3125,0)+$;a.e.style.left=(a.p.w+-0.0)*0.0094+$;a.w=Math.max((a.p.w+-0.0)*0.3125,0);a.e.style.height=Math.max((a.p.h+-6)*1,0)+$;a.e.style.top=3+-a.p.py+$;a.h=Math.max((a.p.h+-6)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-6)*1,0),0)}catch(fb){}try{a=b[C]={e:document.getElementById(wa),w:0,h:0,py:0,p:b[z]};a.e.style.width=16+$;a.e.style.left=(a.p.w+-16)*0.5+$;a.w=16;a.h=16;a.p.py=a.p.py+Math.max(16,0)}catch(gb){}try{a=
b[A]={e:document.getElementById(ta),w:0,h:0,py:0,p:b[v]};a.e.style.width=Math.max((a.p.w+-0.0)*0.3125,0)+$;a.e.style.left=(a.p.w+-0.0)*0.3406+$;a.w=Math.max((a.p.w+-0.0)*0.3125,0);a.e.style.height=Math.max((a.p.h+-6)*1,0)+$;a.e.style.top=3+-a.p.py+$;a.h=Math.max((a.p.h+-6)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-6)*1,0),0)}catch(hb){}try{a=b[D]={e:document.getElementById(ua),w:0,h:0,py:0,p:b[A]};a.e.style.width=16+$;a.e.style.left=(a.p.w+-16)*0.5+$;a.w=16;a.h=16;a.p.py=a.p.py+Math.max(16,0)}catch(ib){}try{a=
b[B]={e:document.getElementById(xa),w:0,h:0,py:0,p:b[v]};a.e.style.width=Math.max((a.p.w+-0.0)*0.3125,0)+$;a.e.style.left=(a.p.w+-0.0)*0.6719+$;a.w=Math.max((a.p.w+-0.0)*0.3125,0);a.e.style.height=Math.max((a.p.h+-6)*1,0)+$;a.e.style.top=3+-a.p.py+$;a.h=Math.max((a.p.h+-6)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-6)*1,0),0)}catch(jb){}try{a=b[E]={e:document.getElementById(ya),w:0,h:0,py:0,p:b[B]};a.e.style.width=16+$;a.e.style.left=(a.p.w+-16)*0.5+$;a.w=16;a.h=16;a.p.py=a.p.py+Math.max(16,0)}catch(kb){}}},
"list":{"id":ka,"anchor_id":g,"resize":function(d,e){var a;var b={};var I;a=b[H]={w:d,h:e,py:0};try{a=b[G]={e:document.getElementById(Ka),w:0,h:0,py:0,p:b[H]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=Math.max((a.p.h+-40)*1,0)+$;a.e.style.top=40+-a.p.py+$;a.h=Math.max((a.p.h+-40)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-40)*1,0),0)}catch(J){}try{a=b[Q]={e:document.getElementById(La),w:0,h:0,py:0,p:b[G]};a.conth=a.e.getAttribute(m);a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=(a.conth||
(2147483647<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(1500,Math.max((a.p.h+-0.0)*1,0))))+$;a.e.style.top=0+-a.p.py+$;a.h=a.conth||(2147483647<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(1500,Math.max((a.p.h+-0.0)*1,0)));a.p.py=a.p.py+Math.max(a.conth||(2147483647<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(1500,Math.max((a.p.h+-0.0)*1,0))),0+0)}catch(K){}try{a=b[R]={w:0,h:0,py:0,p:b[Q]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=89;a.p.py=a.p.py+
Math.max(89,0)}catch(L){}try{a=b[S]={w:0,h:0,py:0,p:b[R]};a.w=Math.max((a.p.w+-18)*1,0);a.h=44;a.p.py=a.p.py+Math.max(44,0)}catch(M){}try{a=b[U]={e:document.getElementById(Ia),w:0,h:0,py:0,p:b[S]};a.w=Math.max((a.p.w+20)*1,0);a.e.style.height=Math.max((a.p.h+-0.0)*1,0)+$;a.e.style.top=0+-a.p.py+$;a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(N){}try{a=b[aa]={e:document.getElementById(Ga),w:0,h:0,py:0,p:b[U]};a.w=9;a.e.style.height=13+$;a.e.style.top=(a.p.h+
-13)*0.4839+-a.p.py+$;a.h=13;a.p.py=a.p.py+Math.max(13,0)}catch(Ta){}try{a=b[ba]={e:document.getElementById(Na),w:0,h:0,py:0,p:b[U]};a.w=33;a.e.style.height=23+$;a.e.style.top=(a.p.h+-23)*0.4762+-a.p.py+$;a.h=23;a.p.py=a.p.py+Math.max(23,0)}catch(Ua){}try{a=b[O]={e:document.getElementById(Ja),w:0,h:0,py:0,p:b[H]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=43+$;a.e.style.top=0+-a.p.py+$;a.h=43;a.p.py=a.p.py+Math.max(43,0)}catch(Va){}try{a=b[ca]={e:document.getElementById(Ha),w:0,h:0,py:0,p:b[O]};
a.w=60;a.e.style.height=30+$;a.e.style.top=(a.p.h+-36)*1+-a.p.py+$;a.h=30;a.p.py=a.p.py+Math.max(30,5+5)}catch(Wa){}try{a=b[da]={e:document.getElementById(Ma),w:0,h:0,py:0,p:b[O]};a.e.style.width=170+$;a.e.style.left=(a.p.w+-170)*0.5+$;a.w=170;a.e.style.height=25+$;a.e.style.top=(a.p.h+-34)*1+-a.p.py+$;a.h=25;a.p.py=a.p.py+Math.max(25,0)}catch(Xa){}try{a=b[P]={e:document.getElementById(Ca),w:0,h:0,py:0,p:b[H]};a.w=0;a.e.style.height=0+$;a.e.style.top=3E3+-a.p.py+$;a.h=0;a.p.py=a.p.py+Math.max(0,0)}catch(Ya){}}},
"landing":{"id":ja,"anchor_id":f,"resize":function(d,e){var a;var b={};var I;a=b[W]={w:d,h:e,py:0};try{a=b[V]={w:0,h:0,py:0,p:b[W]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=43;a.p.py=a.p.py+Math.max(43,0)}catch(J){}try{a=b[ea]={e:document.getElementById(Da),w:0,h:0,py:0,p:b[V]};a.w=60;a.e.style.height=30+$;a.e.style.top=(a.p.h+-36)*1+-a.p.py+$;a.h=30;a.p.py=a.p.py+Math.max(30,5+5)}catch(K){}try{a=b[fa]={e:document.getElementById(Fa),w:0,h:0,py:0,p:b[V]};a.e.style.width=111+$;a.e.style.left=(a.p.w+-111)*
0.4976+$;a.w=111;a.e.style.height=25+$;a.e.style.top=(a.p.h+-34)*1+-a.p.py+$;a.h=25;a.p.py=a.p.py+Math.max(25,0)}catch(L){}try{a=b[X]={w:0,h:0,py:0,p:b[W]};a.w=320;a.h=417;a.p.py=a.p.py+Math.max(417,0)}catch(M){}try{a=b[ha]={e:document.getElementById(Ea),w:0,h:0,py:0,p:b[X]};a.conth=a.e.getAttribute(m);a.w=Math.max((a.p.w+-2)*1,0);a.e.style.height=(a.conth||(-1<Math.max((a.p.h+-2)*1,0)?Math.max((a.p.h+-2)*1,0):Math.max(415,Math.max((a.p.h+-2)*1,0))))+$;a.e.style.top=0+-a.p.py+$;a.h=a.conth||(-1<Math.max((a.p.h+
-2)*1,0)?Math.max((a.p.h+-2)*1,0):Math.max(415,Math.max((a.p.h+-2)*1,0)));a.p.py=a.p.py+Math.max(a.conth||(-1<Math.max((a.p.h+-2)*1,0)?Math.max((a.p.h+-2)*1,0):Math.max(415,Math.max((a.p.h+-2)*1,0))),0+0)}catch(N){}}}};m1Design[l]=Sa;m1Design[Oa]=Za;m1Design[j]={};m1Design[k]=h;m1Design[Ra]=true;m1Design[Qa]=true;m1Design[Pa]=function(){return i}})(); return m1Design; }();m1Design.actions={'action3':function() { phoneui.gotoMultiPagePage('m1-UNT-Appv2-multiPage1', 'SET_PAGE', 'm1-UNT-Appv2-DiscountStatus', 'NONE');},
'action0':function() { phoneui.gotoMultiPagePage('m1-UNT-Appv2-multiPage1', 'SET_PAGE', 'm1-UNT-Appv2-Map', 'NONE');},
'action2':function() { phoneui.gotoMultiPagePage('m1-UNT-Appv2-multiPage1', 'SET_PAGE', 'm1-UNT-Appv2-Settings', 'NONE');},
'action7':function() { phoneui.gotoScreen('m1-UNT_Appv2', 'SLIDE_RIGHT');},
'action6':function() { phoneui.gotoScreen('m1-landing', 'DEFAULT');},
'action8':function() { phoneui.gotoScreen('m1-list', 'DEFAULT');},
'action4':function() { phoneui.gotoScreen('m1-list', 'SLIDE_RIGHT');}};
;
