var m1Design = function() { m1Design = {}; var c="#m1-UNT_Appv2";var d="NEVER";var e="UNT_Appv2";var f="_resizing";var g="ajaxPageReloadApproach";var h="css";var i="data-layout-content-height";var j="e0";var k="e1";var l="e10";var n="e11";var o="e12";var p="e13";var q="e14";var r="e15";var s="e16";var t="e17";var u="e18";var v="e19";var w="e2";var x="e20";var y="e21";var z="e22";var A="e23";var B="e3";var C="e30";var D="e31";var E="e37";var F="e38";var G="e39";var H="e4";var I="e40";var J="e42";var K="e44";var L="e5";var M="e6";var N="e7";
var O="e8";var P="e9";var Q="m1-";var R="m1-UNT-Appv2-DiscountStatus-box";var S="m1-UNT-Appv2-DiscountStatus-box-scroller";var T="m1-UNT-Appv2-Map-box";var U="m1-UNT-Appv2-MapOfGarage";var V="m1-UNT-Appv2-Settings-box";var W="m1-UNT-Appv2-Settings-box-scroller";var X="m1-UNT-Appv2-TextList1";var Y="m1-UNT-Appv2-TextList2";var Z="m1-UNT-Appv2-accessoryImage1";var aa="m1-UNT-Appv2-accessoryImage2";var ba="m1-UNT-Appv2-multiPage1";var ca="m1-UNT-Appv2-tabBar";var da="m1-UNT-Appv2-tabBar-DiscountStatus";
var ea="m1-UNT-Appv2-tabBar-DiscountStatus-img";var fa="m1-UNT-Appv2-tabBar-Map";var ga="m1-UNT-Appv2-tabBar-Map-img";var ha="m1-UNT-Appv2-tabBar-Settings";var ia="m1-UNT-Appv2-tabBar-Settings-img";var ja="m1-UNT-Appv2-text1";var ka="m1-UNT-Appv2-text2";var la="m1-UNT-Appv2-text3";var ma="pages";var $="px";var na="root";var oa="shouldHideAddressBar";var pa="softSpinnerEnabled";
(function(){var qa=function(m){return Q+m};var sa={"UNT_Appv2":{"id":e,"anchor_id":c,"resize":function(m,ra){var a;var b={};var ta;a=b[k]={w:m,h:ra,py:0};try{a=b[j]={e:document.getElementById(ba),w:0,h:0,py:0,p:b[k]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=Math.max((a.p.h+-49)*1,0)+$;a.e.style.top=0+-a.p.py+$;a.h=Math.max((a.p.h+-49)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-49)*1,0),0)}catch(ua){}try{a=b[H]={w:0,h:0,py:0,p:b[j]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=Math.max((a.p.h+-0.0)*
1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(va){}try{a=b[B]={e:document.getElementById(T),w:0,h:0,py:0,p:b[H]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=Math.max((a.p.h+-0.0)*1,0)+$;a.e.style.top=0+-a.p.py+$;a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(wa){}try{a=b[L]={w:0,h:0,py:0,p:b[B]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=43;a.p.py=a.p.py+Math.max(43,0)}catch(xa){}try{a=b[M]={e:document.getElementById(ka),w:0,h:0,py:0,p:b[L]};
a.e.style.width=40+$;a.e.style.left=(a.p.w+-40)*0.5+$;a.w=40;a.e.style.height=23+$;a.e.style.top=(a.p.h+-33)*1+-a.p.py+$;a.h=23;a.p.py=a.p.py+Math.max(23,0)}catch(ya){}try{a=b[N]={w:0,h:0,py:0,p:b[B]};a.w=320;a.h=368;a.p.py=a.p.py+Math.max(368,0)}catch(za){}try{a=b[O]={e:document.getElementById(U),w:0,h:0,py:0,p:b[N]};a.conth=a.e.getAttribute(i);a.w=Math.max((a.p.w+-2)*1,0);a.e.style.height=(a.conth||(-1<Math.max((a.p.h+-2)*1,0)?Math.max((a.p.h+-2)*1,0):Math.max(366,Math.max((a.p.h+-2)*1,0))))+$;
a.e.style.top=0+-a.p.py+$;a.h=a.conth||(-1<Math.max((a.p.h+-2)*1,0)?Math.max((a.p.h+-2)*1,0):Math.max(366,Math.max((a.p.h+-2)*1,0)));a.p.py=a.p.py+Math.max(a.conth||(-1<Math.max((a.p.h+-2)*1,0)?Math.max((a.p.h+-2)*1,0):Math.max(366,Math.max((a.p.h+-2)*1,0))),0+0)}catch(Aa){}try{a=b[l]={w:0,h:0,py:0,p:b[j]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(Ba){}try{a=b[P]={e:document.getElementById(R),w:0,h:0,py:0,p:b[l]};a.w=Math.max((a.p.w+
-0.0)*1,0);a.e.style.height=Math.max((a.p.h+-0.0)*1,0)+$;a.e.style.top=0+-a.p.py+$;a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(Ca){}try{a=b[n]={e:document.getElementById(S),w:0,h:0,py:0,p:b[P]};a.conth=a.e.getAttribute(i);a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=(a.conth||(2147483647<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(511,Math.max((a.p.h+-0.0)*1,0))))+$;a.e.style.top=0+-a.p.py+$;a.h=a.conth||(2147483647<Math.max((a.p.h+
-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(511,Math.max((a.p.h+-0.0)*1,0)));a.p.py=a.p.py+Math.max(a.conth||(2147483647<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(511,Math.max((a.p.h+-0.0)*1,0))),0+0)}catch(Da){}try{a=b[o]={w:0,h:0,py:0,p:b[n]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=43;a.p.py=a.p.py+Math.max(43,0)}catch(Ea){}try{a=b[p]={e:document.getElementById(la),w:0,h:0,py:0,p:b[o]};a.e.style.width=147+$;a.e.style.left=(a.p.w+-147)*0.4971+$;a.w=147;a.e.style.height=23+$;a.e.style.top=
(a.p.h+-33)*1+-a.p.py+$;a.h=23;a.p.py=a.p.py+Math.max(23,0)}catch(Fa){}try{a=b[q]={w:0,h:0,py:0,p:b[n]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=88;a.p.py=a.p.py+Math.max(88,0)}catch(Ga){}try{a=b[r]={w:0,h:0,py:0,p:b[q]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=44;a.p.py=a.p.py+Math.max(44,0)}catch(Ha){}try{a=b[s]={e:document.getElementById(Z),w:0,h:0,py:0,p:b[r]};a.w=9;a.e.style.height=13+$;a.e.style.top=(a.p.h+-13)*0.4839+-a.p.py+$;a.h=13;a.p.py=a.p.py+Math.max(13,0)}catch(Ia){}try{a=b[t]={e:document.getElementById(X),
w:0,h:0,py:0,p:b[r]};a.w=84;a.e.style.height=23+$;a.e.style.top=(a.p.h+-23)*0.4762+-a.p.py+$;a.h=23;a.p.py=a.p.py+Math.max(23,0)}catch(Ja){}try{a=b[u]={w:0,h:0,py:0,p:b[q]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=44;a.p.py=a.p.py+Math.max(44,0)}catch(Ka){}try{a=b[v]={e:document.getElementById(aa),w:0,h:0,py:0,p:b[u]};a.w=9;a.e.style.height=13+$;a.e.style.top=(a.p.h+-13)*0.4839+-a.p.py+$;a.h=13;a.p.py=a.p.py+Math.max(13,0)}catch(La){}try{a=b[x]={e:document.getElementById(Y),w:0,h:0,py:0,p:b[u]};a.w=84;
a.e.style.height=23+$;a.e.style.top=(a.p.h+-23)*0.4762+-a.p.py+$;a.h=23;a.p.py=a.p.py+Math.max(23,0)}catch(Ma){}try{a=b[z]={w:0,h:0,py:0,p:b[j]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-0.0)*1,0),0)}catch(Na){}try{a=b[y]={e:document.getElementById(V),w:0,h:0,py:0,p:b[z]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=Math.max((a.p.h+-0.0)*1,0)+$;a.e.style.top=0+-a.p.py+$;a.h=Math.max((a.p.h+-0.0)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+
-0.0)*1,0),0)}catch(Oa){}try{a=b[A]={e:document.getElementById(W),w:0,h:0,py:0,p:b[y]};a.conth=a.e.getAttribute(i);a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=(a.conth||(180<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0))))+$;a.e.style.top=0+-a.p.py+$;a.h=a.conth||(180<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0)));a.p.py=a.p.py+Math.max(a.conth||(180<Math.max((a.p.h+-0.0)*1,0)?Math.max((a.p.h+-0.0)*
1,0):Math.max(411,Math.max((a.p.h+-0.0)*1,0))),0+0)}catch(Pa){}try{a=b[C]={w:0,h:0,py:0,p:b[A]};a.w=Math.max((a.p.w+-0.0)*1,0);a.h=43;a.p.py=a.p.py+Math.max(43,0)}catch(Qa){}try{a=b[D]={e:document.getElementById(ja),w:0,h:0,py:0,p:b[C]};a.e.style.width=76+$;a.e.style.left=(a.p.w+-76)*0.5+$;a.w=76;a.e.style.height=23+$;a.e.style.top=(a.p.h+-33)*1+-a.p.py+$;a.h=23;a.p.py=a.p.py+Math.max(23,0)}catch(Ra){}try{a=b[w]={e:document.getElementById(ca),w:0,h:0,py:0,p:b[k]};a.w=Math.max((a.p.w+-0.0)*1,0);a.e.style.height=
49+$;a.e.style.top=(a.p.h+-49)*1+-a.p.py+$;a.h=49;a.p.py=a.p.py+Math.max(49,0)}catch(Sa){}try{a=b[E]={e:document.getElementById(fa),w:0,h:0,py:0,p:b[w]};a.e.style.width=Math.max((a.p.w+-0.0)*0.3125,0)+$;a.e.style.left=(a.p.w+-0.0)*0.0094+$;a.w=Math.max((a.p.w+-0.0)*0.3125,0);a.e.style.height=Math.max((a.p.h+-6)*1,0)+$;a.e.style.top=3+-a.p.py+$;a.h=Math.max((a.p.h+-6)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-6)*1,0),0)}catch(Ta){}try{a=b[I]={e:document.getElementById(ga),w:0,h:0,py:0,p:b[E]};a.e.style.width=
16+$;a.e.style.left=(a.p.w+-16)*0.5+$;a.w=16;a.h=16;a.p.py=a.p.py+Math.max(16,0)}catch(Ua){}try{a=b[F]={e:document.getElementById(da),w:0,h:0,py:0,p:b[w]};a.e.style.width=Math.max((a.p.w+-0.0)*0.3125,0)+$;a.e.style.left=(a.p.w+-0.0)*0.3406+$;a.w=Math.max((a.p.w+-0.0)*0.3125,0);a.e.style.height=Math.max((a.p.h+-6)*1,0)+$;a.e.style.top=3+-a.p.py+$;a.h=Math.max((a.p.h+-6)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-6)*1,0),0)}catch(Va){}try{a=b[J]={e:document.getElementById(ea),w:0,h:0,py:0,p:b[F]};
a.e.style.width=16+$;a.e.style.left=(a.p.w+-16)*0.5+$;a.w=16;a.h=16;a.p.py=a.p.py+Math.max(16,0)}catch(Wa){}try{a=b[G]={e:document.getElementById(ha),w:0,h:0,py:0,p:b[w]};a.e.style.width=Math.max((a.p.w+-0.0)*0.3125,0)+$;a.e.style.left=(a.p.w+-0.0)*0.6719+$;a.w=Math.max((a.p.w+-0.0)*0.3125,0);a.e.style.height=Math.max((a.p.h+-6)*1,0)+$;a.e.style.top=3+-a.p.py+$;a.h=Math.max((a.p.h+-6)*1,0);a.p.py=a.p.py+Math.max(Math.max((a.p.h+-6)*1,0),0)}catch(Xa){}try{a=b[K]={e:document.getElementById(ia),w:0,
h:0,py:0,p:b[G]};a.e.style.width=16+$;a.e.style.left=(a.p.w+-16)*0.5+$;a.w=16;a.h=16;a.p.py=a.p.py+Math.max(16,0)}catch(Ya){}}}};m1Design[h]=qa;m1Design[ma]=sa;m1Design[f]={};m1Design[g]=d;m1Design[pa]=true;m1Design[oa]=true;m1Design[na]=function(){return e}})(); return m1Design; }();m1Design.actions={'action3':function() { phoneui.gotoMultiPagePage('m1-UNT-Appv2-multiPage1', 'SET_PAGE', 'm1-UNT-Appv2-DiscountStatus', 'NONE');},
'action0':function() { phoneui.gotoMultiPagePage('m1-UNT-Appv2-multiPage1', 'SET_PAGE', 'm1-UNT-Appv2-Map', 'NONE');},
'action2':function() { phoneui.gotoMultiPagePage('m1-UNT-Appv2-multiPage1', 'SET_PAGE', 'm1-UNT-Appv2-Settings', 'NONE');}};
;
