// Generated by MobiOne.
// This file is intentionally empty. It serves as a placeholder for the actual api
// version that is dynamically substituted in place of this file by App Center Builder
// or the Mobile Web Simulator. DO NOT MODIFY OR DELETE THIS FILE.